export { TRDashboard } from './dashboard/index'
export { TRListPage } from './list/index'
export { TRReviewPage } from './review/index'
export { TRViewPage } from './view/index'
export { TRWizardPage } from './wizard/index'
