/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrsRouteImport } from './routes/_authenticated/trs'
import { Route as AuthenticatedNovoTrRouteImport } from './routes/_authenticated/novo-tr'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedTrTrIdRouteImport } from './routes/_authenticated/tr.$trId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrsRoute = AuthenticatedTrsRouteImport.update({
  id: '/trs',
  path: '/trs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoTrRoute = AuthenticatedNovoTrRouteImport.update({
  id: '/novo-tr',
  path: '/novo-tr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrTrIdRoute = AuthenticatedTrTrIdRouteImport.update({
  id: '/tr/$trId',
  path: '/tr/$trId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/novo-tr': typeof AuthenticatedNovoTrRoute
  '/trs': typeof AuthenticatedTrsRoute
  '/tr/$trId': typeof AuthenticatedTrTrIdRoute
}
export interface FileRoutesByTo {
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/novo-tr': typeof AuthenticatedNovoTrRoute
  '/trs': typeof AuthenticatedTrsRoute
  '/': typeof AuthenticatedIndexRoute
  '/tr/$trId': typeof AuthenticatedTrTrIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/novo-tr': typeof AuthenticatedNovoTrRoute
  '/_authenticated/trs': typeof AuthenticatedTrsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tr/$trId': typeof AuthenticatedTrTrIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovacoes'
    | '/dashboard'
    | '/novo-tr'
    | '/trs'
    | '/tr/$trId'
  fileRoutesByTo: FileRoutesByTo
  to: '/aprovacoes' | '/dashboard' | '/novo-tr' | '/trs' | '/' | '/tr/$trId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/novo-tr'
    | '/_authenticated/trs'
    | '/_authenticated/'
    | '/_authenticated/tr/$trId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trs': {
      id: '/_authenticated/trs'
      path: '/trs'
      fullPath: '/trs'
      preLoaderRoute: typeof AuthenticatedTrsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-tr': {
      id: '/_authenticated/novo-tr'
      path: '/novo-tr'
      fullPath: '/novo-tr'
      preLoaderRoute: typeof AuthenticatedNovoTrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tr/$trId': {
      id: '/_authenticated/tr/$trId'
      path: '/tr/$trId'
      fullPath: '/tr/$trId'
      preLoaderRoute: typeof AuthenticatedTrTrIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNovoTrRoute: typeof AuthenticatedNovoTrRoute
  AuthenticatedTrsRoute: typeof AuthenticatedTrsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTrTrIdRoute: typeof AuthenticatedTrTrIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNovoTrRoute: AuthenticatedNovoTrRoute,
  AuthenticatedTrsRoute: AuthenticatedTrsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTrTrIdRoute: AuthenticatedTrTrIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
